In [44]:
import numpy as np

# Numpy

In [29]:
data = np.random.seed(2131982)
data = np.random.randint(101, size=(10,10))
data

array([[  1,   2,  47,  58,  88,  78, 100,  70,  79,  18],
       [ 21,  73,  19,  15,  12,  73,  87,  60,  27,  10],
       [ 78,  85,  90,  90,  79,  42,   5,  82,  58,  99],
       [ 97,  37,  36,  46,  47,  14,  16,  20,   5,  31],
       [ 87,  13,  17,  53,  38,  46,  47,  32,  58,  62],
       [ 48,  97,  18,  58,  98,  25,  41,  76,  61,  24],
       [ 10,  41,  24,  15,  65,   5,  75,  83,  19,  10],
       [ 94,   8,  26,  62,  23,  14,  72,  43,  21,  46],
       [ 84,  57,  36,  93, 100,  23,  98,  69,  38,  45],
       [ 28,  99,  97,  91,  90,  23,  69,  90,  77,  72]])

## Media aritmética

In [30]:
data.mean()

51.29

## Mediana

In [31]:
np.median(data)

47.0

## Desviación típica

In [33]:
np.std(data)

30.422128459396134

## Varianza

In [35]:
np.var(data)

925.5059000000001

## Media aritmética de cada fila

In [37]:
np.mean(data, axis=1)

array([54.1, 39.7, 70.8, 34.9, 45.3, 54.6, 34.7, 40.9, 64.3, 73.6])

## Media aritmética de cada columna

In [38]:
np.mean(data, axis=0)

array([54.8, 51.2, 41. , 58.1, 64. , 34.3, 61. , 62.5, 44.3, 41.7])

## Desviación típica de cada fila

In [39]:
np.std(data, axis=1)

array([34.06302981, 28.40088027, 27.02147294, 24.61077   , 20.77522563,
       27.51799411, 27.86772327, 26.47054967, 26.95941394, 25.90057914])

## Desviación típica de cada columna

In [41]:
np.std(data, axis=0)

array([35.43105982, 34.76434956, 27.79568312, 26.87173236, 30.46309242,
       23.72361692, 31.15124396, 22.27217996, 24.48285114, 27.64434843])

## Varianza de cada fila

In [42]:
np.var(data, axis=1)

array([1160.29,  806.61,  730.16,  605.69,  431.61,  757.24,  776.61,
        700.69,  726.81,  670.84])

## Varianza de cada columna

In [43]:
np.var(data, axis=0)

array([1255.36, 1208.56,  772.6 ,  722.09,  928.  ,  562.81,  970.4 ,
        496.05,  599.41,  764.21])

# Pandas

In [46]:
import pandas as pd

In [50]:
dataframe = pd.DataFrame(data, index=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], columns=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
dataframe

a   b   c   d    e   f    g   h   i   j
1    1   2  47  58   88  78  100  70  79  18
2   21  73  19  15   12  73   87  60  27  10
3   78  85  90  90   79  42    5  82  58  99
4   97  37  36  46   47  14   16  20   5  31
5   87  13  17  53   38  46   47  32  58  62
6   48  97  18  58   98  25   41  76  61  24
7   10  41  24  15   65   5   75  83  19  10
8   94   8  26  62   23  14   72  43  21  46
9   84  57  36  93  100  23   98  69  38  45
10  28  99  97  91   90  23   69  90  77  72

## Describe

In [51]:
dataframe.describe()

a          b          c          d           e          f  \
count  10.000000  10.000000  10.000000  10.000000   10.000000  10.000000   
mean   54.800000  51.200000  41.000000  58.100000   64.000000  34.300000   
std    37.347616  36.644842  29.299223  28.325293   32.110919  25.006888   
min     1.000000   2.000000  17.000000  15.000000   12.000000   5.000000   
25%    22.750000  19.000000  20.250000  47.750000   40.250000  16.250000   
50%    63.000000  49.000000  31.000000  58.000000   72.000000  24.000000   
75%    86.250000  82.000000  44.250000  83.000000   89.500000  45.000000   
max    97.000000  99.000000  97.000000  93.000000  100.000000  78.000000   

                g          h          i          j  
count   10.000000  10.000000  10.000000  10.000000  
mean    61.000000  62.500000  44.300000  41.700000  
std     32.836294  23.476939  25.807191  29.139702  
min      5.000000  20.000000   5.000000  10.000000  
25%     42.500000  47.250000  22.500000  19.500000  
50%     70.500000  69.500000  48.000000  38.000000  
75%     84.000000  80.500000  60.250000  58.000000  
max    100.000000  90.000000  79.000000  99.000000

## ¿Son coherentes los datos entre Nupy y Pandas?
Sí lo son, primeramente se puede observar que los valores de la mediana de cada columna retornadas por Numpy, son iguales a la descricpción de Pandas; por otro lado, si bien los valores no son iguales para el caso del a desviación estándar, estas se asemejan bastante.